name: AI_Daily_Post
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到了 v4
      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到了 v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: run: pip install google-generativeai
      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot_logic.py
